services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/app.js", "produce"]
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
  consumer1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/app.js", "consume"]
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      GROUP_ID: "group1"
      CONSUMER_ID: "consumer1"
  consumer2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/app.js", "consume"]
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      GROUP_ID: "group1"
      CONSUMER_ID: "consumer2"
  consumer3:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "dist/app.js", "consume"]
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      GROUP_ID: "group2"
      CONSUMER_ID: "consumer3"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
    driver: local